services:
    app.inquiry.get_one:
        class: AppBundle\Fulcrum\Usecase\GetOne
        arguments: ["@app.inquiry_repository"]
        
    app.inquiry.search:
        class: AppBundle\Fulcrum\Usecase\Search
        arguments: ["@app.inquiry_repository"]
        
    app.inquiry.create:
        class: AppBundle\Fulcrum\Usecase\CreateEntity
        arguments: ["@app.inquiry_repository", "@event_dispatcher"]
        
    app.inquiry.update:
        class: AppBundle\Fulcrum\Usecase\UpdateEntity
        arguments: ["@app.inquiry_repository", "@event_dispatcher"]
        
    app.inquiry.remove:
        class: AppBundle\Fulcrum\Usecase\RemoveEntity
        arguments: ["@app.inquiry_repository", "@event_dispatcher"]

    app.inquiry_repository:
        class:  AppBundle\Repository\InquiryRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Inquiry